"""
JavaScript Config Generator - Generate map configuration
"""

import html
import json
import logging
from typing import Dict, List
from qgis.core import QgsMapLayer

log = logging.getLogger(__name__)

from .base_generator import BaseGenerator


class JSConfigGenerator(BaseGenerator):
    """Generator for JavaScript configuration file."""

    def __init__(self, config: Dict):
        """Initialize the JS config generator.

        :param config: Project configuration
        """
        super().__init__(config)

    def generate(self, layers: List[QgsMapLayer], **kwargs) -> Dict:
        """Generate JavaScript configuration.

        :param layers: List of QGIS layers
        :param kwargs: Additional parameters
        :returns: Dictionary with generation results
        """
        results = {
            'success': False,
            'javascript': '',
            'errors': []
        }

        try:
            javascript = self._generate_config(layers)
            results['javascript'] = javascript
            results['success'] = True

        except Exception as e:
            results['errors'].append(f"JS config generation error: {str(e)}")

        return results

    def _generate_config(self, layers: List[QgsMapLayer]) -> str:
        """Generate JavaScript configuration object.

        :param layers: List of QGIS layers
        :returns: JavaScript string
        """
        map_config = self.get_config_value('map', {})
        basemap = self.get_config_value('basemap', {})
        ui_config = self.get_config_value('ui', {})
        theme = self.get_config_value('theme', {})

        layer_configs = []
        for layer in layers:
            layer_id = self.get_layer_id(layer)
            cfg = self.get_config_value(f'layers.{layer.id()}', {})
            if not cfg:
                cfg = self.get_config_value(f'layers.{layer_id}', {})

            layer_configs.append({
                'id': layer_id,
                'name': html.escape(cfg.get('display_name', layer.name()) or layer.name()),
                'visible': cfg.get('visible', True),
                'opacity': cfg.get('opacity', 1.0),
                'type': self._get_layer_type(layer),
                'min_zoom': cfg.get('min_zoom', 0),
                'max_zoom': cfg.get('max_zoom', 22)
            })

        # Serialize layer_configs to valid JSON (True→true, None→null)
        layers_json = json.dumps(layer_configs, ensure_ascii=False, indent=8)

        # Compute WGS84 bounds & center from layers if not explicitly specified
        wgs84_center, wgs84_bounds = self._calculate_layers_wgs84_extent(layers)

        raw_center = map_config.get('center', None)
        if (not raw_center or raw_center == [0, 0]) and wgs84_center:
            center_lat, center_lng = wgs84_center[0], wgs84_center[1]
        elif raw_center:
            center_lat, center_lng = raw_center[0], raw_center[1]
        else:
            center_lat, center_lng = 0, 0

        raw_bounds = map_config.get('bounds', None)
        if raw_bounds is None and wgs84_bounds:
            raw_bounds = wgs84_bounds

        bounds_js = json.dumps(raw_bounds) if raw_bounds is not None else 'null'

        javascript = f"""/**
 * WebGIS Configuration
 * Generated by WebGisMapBuilder
 */

const WebGISConfig = {{
    // Project Information
    project: {{
        title: '{html.escape(self.get_config_value('project.title', 'Web Map'))}',
        description: '{html.escape(self.get_config_value('project.description', ''))}',
        author: '{html.escape(self.get_config_value('project.author', ''))}'
    }},

    // Map Configuration
    map: {{
        center: [{center_lat}, {center_lng}],
        zoom: {map_config.get('zoom', 3)},
        minZoom: {map_config.get('min_zoom', 0)},
        maxZoom: {map_config.get('max_zoom', 20)},
        bounds: {bounds_js}
    }},

    // Basemap Configuration
    basemap: {{
        default: '{basemap.get('provider', 'osm')}',
        providers: {{
            osm: {{
                name: 'OpenStreetMap',
                url: 'https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
                maxZoom: 19
            }},
            carto_positron: {{
                name: 'CartoDB Positron',
                url: 'https://{{s}}.basemaps.cartocdn.com/light_all/{{z}}/{{x}}{{y}}{{r}}.png',
                attribution: '&copy; OpenStreetMap &copy; CARTO',
                maxZoom: 20
            }},
            carto_dark: {{
                name: 'CartoDB Dark',
                url: 'https://{{s}}.basemaps.cartocdn.com/dark_all/{{z}}/{{x}}{{y}}{{r}}.png',
                attribution: '&copy; OpenStreetMap &copy; CARTO',
                maxZoom: 20
            }},
            esri_world: {{
                name: 'ESRI World Imagery',
                url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{{z}}/{{y}}/{{x}}',
                attribution: 'Tiles &copy; Esri',
                maxZoom: 18
            }},
            opentopomap: {{
                name: 'OpenTopoMap',
                url: 'https://{{s}}.tile.opentopomap.org/{{z}}/{{x}}/{{y}}.png',
                attribution: '&copy; OpenStreetMap contributors, SRTM',
                maxZoom: 17
            }}
        }}
    }},

    // Layer Configuration
    layers: {layers_json},

    // UI Configuration
    ui: {{
        showZoomControl: {str(ui_config.get('show_zoom_control', True)).lower()},
        showScaleControl: {str(ui_config.get('show_scale_control', True)).lower()},
        showLayerControl: {str(ui_config.get('show_layer_control', True)).lower()},
        showFullscreen: {str(ui_config.get('show_fullscreen', True)).lower()},
        showMousePosition: {str(ui_config.get('show_mouse_position', True)).lower()},
        showLegend: {str(ui_config.get('show_legend', True)).lower()}
    }},

    // Theme Configuration
    theme: {{
        name: '{theme.get('name', 'professional')}',
        primaryColor: '{theme.get('primary_color', '#2c3e50')}',
        secondaryColor: '{theme.get('secondary_color', '#3498db')}'
    }}
}};"""

        return javascript

    def _calculate_layers_wgs84_extent(self, layers: List[QgsMapLayer]):
        """Calculate combined WGS84 extent and center from layers."""
        try:
            from qgis.core import QgsCoordinateReferenceSystem, QgsCoordinateTransform, QgsProject
            wgs84 = QgsCoordinateReferenceSystem('EPSG:4326')
            project = QgsProject.instance()
            total_extent = None

            for layer in layers:
                if not layer.isValid():
                    continue
                ext = layer.extent()
                if ext.isEmpty() or ext.isNull():
                    continue
                try:
                    if layer.crs() != wgs84:
                        ct = QgsCoordinateTransform(layer.crs(), wgs84, project)
                        ext_wgs = ct.transformBoundingBox(ext)
                    else:
                        ext_wgs = ext

                    if total_extent is None:
                        total_extent = ext_wgs
                    else:
                        total_extent.combineExtentWith(ext_wgs)
                except Exception as e:  # noqa: BLE001
                    log.warning("Could not transform extent for layer '%s': %s", layer.name(), e)

            if total_extent and not total_extent.isEmpty():
                center = [total_extent.center().y(), total_extent.center().x()]
                bounds = [
                    [total_extent.yMinimum(), total_extent.xMinimum()],
                    [total_extent.yMaximum(), total_extent.xMaximum()]
                ]
                return center, bounds
        except Exception as e:  # noqa: BLE001
            log.warning("Could not calculate WGS84 extent: %s", e)
        return None, None

    def _get_layer_type(self, layer: QgsMapLayer) -> str:
        """Get layer geometry type."""
        from qgis.core import QgsMapLayer, QgsWkbTypes

        if layer.type() == QgsMapLayer.VectorLayer:
            geom_type = layer.geometryType()
            type_map = {
                QgsWkbTypes.PointGeometry: 'point',
                QgsWkbTypes.LineGeometry: 'line',
                QgsWkbTypes.PolygonGeometry: 'polygon'
            }
            return type_map.get(geom_type, 'unknown')
        return 'raster'

    def validate(self) -> tuple:
        """Validate JS config generator configuration.

        :returns: Tuple of (is_valid, error_messages)
        """
        errors = []
        if not self.get_config_value('map.center'):
            errors.append("Map center not configured")
        return (len(errors) == 0, errors)