// WebGisMapBuilder - Basic Map Template
// Generated by WebGisMapBuilder QGIS Plugin

(function() {
    'use strict';

    // Map configuration
    var mapConfig = {
        center: [{{center}}],
        zoom: {{zoom}},
        minZoom: {{min_zoom}},
        maxZoom: {{max_zoom}}
    };

    // Initialize the map
    var map = L.map('map', mapConfig);

    // Add basemap
    var basemap = L.tileLayer('{{basemap_url}}', {
        attribution: '{{basemap_attribution}}',
        maxZoom: {{basemap_max_zoom}}
    }).addTo(map);

    // Layer management
    var layerGroups = {
        baseLayers: {
            'Basemap': basemap
        },
        overlays: {}
    };

    // Load layers
    {{layer_loading_code}}

    // Add layer control
    {{layer_control_code}}

    // Fit map to layer bounds
    function fitMapToBounds() {
        var bounds = null;
        Object.values(layerGroups.overlays).forEach(function(layer) {
            if (layer.getBounds) {
                if (bounds) {
                    bounds.extend(layer.getBounds());
                } else {
                    bounds = layer.getBounds();
                }
            }
        });

        if (bounds) {
            map.fitBounds(bounds);
        }
    }

    // Custom popup function
    function createPopupContent(feature, layer) {
        var properties = feature.properties || {};
        var content = '<div class="popup-content">';

        // Add name if present
        if (properties.name) {
            content += '<div class="popup-header">' + properties.name + '</div>';
        }

        // Add all properties
        for (var key in properties) {
            if (properties.hasOwnProperty(key) && key !== 'name') {
                content += '<div class="popup-field">';
                content += '<span class="popup-label">' + formatLabel(key) + ':</span> ';
                content += '<span class="popup-value">' + formatValue(properties[key]) + '</span>';
                content += '</div>';
            }
        }

        content += '</div>';
        return content;
    }

    // Format label for display
    function formatLabel(key) {
        return key.charAt(0).toUpperCase() + key.slice(1).replace(/_/g, ' ');
    }

    // Format value for display
    function formatValue(value) {
        if (value === null || value === undefined) {
            return '';
        }
        return String(value);
    }

    // Error handling
    window.addEventListener('error', function(e) {
        console.error('Web map error:', e.message);
    });

    // Initialize
    document.addEventListener('DOMContentLoaded', function() {
        console.log('Web map initialized successfully');
        fitMapToBounds();
    });

})();
